services:
  db:
    image: mysql:8.3
    container_name: wallet_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=wallet_db
    ports:
      - "3306:3306"
    volumes:
      - wallet_db:/var/lib/mysql

  wallet:
    image: "khalaimovda/wallet:0.1.0"
    container_name: wallet
    restart: always
    command: "python wallet/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DB_USER: "user"
      DB_PASS: "pass"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_NAME: "wallet_db"
      SECRET_KEY: "django-insecure-ip6j4oh@0_96t$5xi2(plul^bf)j6geql3buius_s^u3vunc!q"
    depends_on:
      - db

volumes:
  wallet_db:
